name: run script

on:
  schedule:
    - cron: '20 22 * * 5' # Everyday at 7pm Brzil time
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # install the python version needed
          
      - name: install python packages
        run: |
          cd /
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run scrap.py
        env:
          SECRET_CHANNEL: ${{ secrets.SECRET_CHANNEL }}
        run: python scrap.py
